# Generated by Django 2.1.7 on 2019-04-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
