# Generated by Django 2.1.7 on 2019-04-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0006_auto_20190403_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='imageName',
            field=models.CharField(default='default.png', max_length=100),
        ),
    ]
