# Generated by Django 2.1.7 on 2019-04-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0008_installedsoftware'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='floatingIp',
            field=models.CharField(default='172.21.1.176', max_length=100),
            preserve_default=False,
        ),
    ]
