# Generated by Django 2.1.7 on 2019-04-13 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0009_instance_floatingip'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedsoftware',
            name='instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance', to='cloud.Instance'),
        ),
    ]
