# Generated by Django 2.1.7 on 2019-04-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0011_auto_20190413_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='instanceName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
